#!/bin/bash

echo "Installing ansible..."

if [[ $(uname) == 'Linux' ]]; then
    echo "Operating system (Linux)"
    sudo apt update
    sudo apt install software-properties-common
    sudo add-apt-repository -y --update ppa:ansible/ansible
    sudo apt install -y ansible
elif [[ $(uname) == 'Darwin' ]]; then
    echo "Operating system (macOs)"
    python3 -m pip install --user ansible
fi
