- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - basic
      - config
      - environment
      - nvim
      - productivity
      - slack
  tasks:
    - include: tasks/basic.yml
    - include: tasks/config.yml
    - include: tasks/environment.yml
    - include: tasks/nvim.yml
    - include: tasks/productivity.yml
    - include: tasks/slack.yml
    - include: tasks/virtualbox.yml
