- name: Add universe repository
  become: true
  become_user: root
  ansible.builtin.apt_repository:
      repo:  deb http://archive.ubuntu.com/ubuntu focal universe
      state: present
  tags:
    - basic

- name: Install basic tools
  become: true
  become_user: root
  apt:
    state: present
    name:
      - software-properties-common
      - git
      - make
      - wget
      - stow
      - python3-pip
  tags:
    - basic

- name: Uninstall basic tools
  become: true
  become_user: root
  apt:
    state: absent
    name:
      - stow
  tags:
    - clean_env
