- name: Download config repository
  ansible.builtin.git:
    repo: 'https://github.com/miguelmoraperea/config.git'
    dest: "{{ lookup('env', 'HOME') }}/Desktop/git/config"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - config
