- name: Add Alacritty repository
  become: true
  become_user: root
  ansible.builtin.apt_repository:
      repo:  ppa:aslatter/ppa
      state: present
  tags:
    - environment

- name: Install environment tools
  become: true
  become_user: root
  apt:
    state: present
    name:
    - alacritty
    - tmux
    - i3-wm
    - i3blocks
  tags:
    - environment

- name: Install fonts
  become: true
  become_user: root
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
  tags:
    - environment
