- name: Add Alacritty repository
  become: true
  become_user: root
  ansible.builtin.apt_repository:
      repo:  ppa:aslatter/ppa
      state: present
  tags:
    - environment

- name: Install environment tools
  become: true
  become_user: root
  apt:
    state: present
    name:
    - alacritty
    - tmux
    - i3-wm
    - i3blocks
  tags:
    - environment

- name: Download Nerd-Fonts repository
  ansible.builtin.git:
    repo: 'https://github.com/ryanoasis/nerd-fonts'
    dest: "{{ lookup('env', 'HOME') }}/Desktop/git/nerd-fonts"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - environment
    - fonts

- name: Install JetBrains font
  become: true
  become_user: root
  shell: /bin/bash -c "$(cd ~/Deskstop/git/nerd-fonts && ./install JetBrainsMono)"
  tags:
    - environment
    - fonts
